version: '3'
services:
  blog:
    restart: always
    build:
        context: /home/xwx/blog-oranges/
        dockerfile: /home/xwx/blog-oranges/Dockerfile
    image: blog:latest
    container_name: hexo-blog
    ports:
      - "8080:4000"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - /home/xwx/blog-oranges:/hexo
    environment:
      TZ: 'Asia/Shanghai'
