version: '3'
services:
  blog:
    restart: always
    build:
        context: /root/blog-oranges/dockerfile
        dockerfile: Dockerfile
    image: blog:latest
    container_name: blog-oranges
    ports:
      - "8080:4000"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - /root/blog-orange:/hexo
    environment:
      TZ: 'Asia/Shanghai'
